<?php

namespace App\Models\Activity;

use Illuminate\Database\Eloquent\Model;

class Specification extends Model
{
    protected $table = 'specification'; // 活动规格表

    protected $fillable = ['uid', 'aid', 'title', 'stint', 'price', 'remainder'];

    static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($query){
            $query->remainder = $query->stint;
        });
    }

}
