<?php

namespace App\Models;

use App\Models\Traits\AreaTrait;
use App\Models\Traits\ImageUrlTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Store extends Model
{
    use AreaTrait, ImageUrlTrait;
    static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    protected $fillable = [
        'user_id', 'name', 'province', 'city', 'district', 'address',
        'latitude', 'longitude', 'contact_name', 'contact_mobile', 'full_address', 'image', 'images'
    ];


    public function user(){
        return $this->belongsTo(User::class, 'user_id');
    }


    public function setImagesAttribute($images)
    {
        $this->attributes['images'] = json_encode($images);
    }

    public function getImagesAttribute($images)
    {
        $newImages = [];
        $oldImages = json_decode($images, true);
        if(!empty($oldImages)){
            foreach ($oldImages as $image){
                // 如果 image 字段本身就已经是完整的 url 就直接返回
                if (Str::startsWith($image, ['http://', 'https://'])) {
                    $newImages[] = $image;
                }else{
                    $newImages[] = Storage::disk('public')->url($image);
                }
            }
        }

        return $newImages;
    }

    public static function addDefaultStore($data){
         $areaInfo = Area::query()->whereIn('code', [
             $data['province'], $data['city'], $data['district']
        ])->pluck('name')->toArray();
        $areaInfo[] = $data['address'];
        $data['full_address'] = implode('-', $areaInfo);
        $area = self::getAreaInfo(implode($areaInfo));
        $data['latitude'] = $area['latitude'];
        $data['longitude'] = $area['longitude'];
        return self::create($data);
    }

    // 根据地址获取经纬度
    protected static function getAreaInfo($address){
        $latitude = '22.6093910000';
        $longitude = '114.0293780000';
        try{
            $response = file_get_contents(sprintf('https://apis.map.qq.com/ws/place/v1/search?boundary=region(全国)&keyword=%s&key=%s', $address, env('TENCENT_MAP_API_KEY')));
            $response = json_decode($response, true);
            if(isset($response['data']) && count($response['data']) > 0){
                $areaInfo = array_shift($response['data']);
                $latitude = $areaInfo['location']['lat'];
                $longitude = $areaInfo['location']['lng'];
            }

        }catch (\Exception $exception){
            \Log::info($exception->getMessage());
        }

        return [
            'latitude' => $latitude,
            'longitude' => $longitude
        ];

    }
    

}
