<?php

namespace App\Models;

use App\Models\Traits\UserAvatarHelper;
use App\Models\User\UserApplyAgent;
use App\Models\User\UserAuth;
use App\Models\User\UserBalance;
use App\Models\User\UserBalanceLog;
use App\Models\User\UserBank;
use App\Models\User\UserRelation;
use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens,Notifiable,UserAvatarHelper;

    const USER_TYPE_ONE = 1;
    const USER_TYPE_TWO = 2;


    //  名片完善情况
    const COMPLETE_PERFECTION = 1;// 已完善
    const INCOMPLETE = 2; // 信息不全
    const TO_BE_IMPROVED = 3; // 待完善


    const IS_ADMIN_TRUE = true;
    const IS_ADMIN_FALSE = false;


    protected $appends = [
        'type_show',
        'companyCardStatus', // 企业会员状态
        'perfect', // 名片完善情况
        'set_cash', // 密码是否为空
    ];

    static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function ($user){
            // 新注册的用户给予新的资金密钥
            UserBalance::addDefaultData($user->id);
        });
    }


    public function getUserType($type = '') {
        $data = [
            self::USER_TYPE_ONE => '普通用户',
            self::USER_TYPE_TWO => '企业会员',
        ];
        return $data[$type] ?? $data;
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
   /* protected $fillable = [
        'name', 'email', 'password',
    ];*/

    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'cash_password',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin' => 'boolean',
    ];

    protected $dates = ['enterprise_at'];


    public function addresses()
    {
        return $this->hasMany(UserAddress::class);
    }

    public function favoriteProducts()
    {
        return $this->belongsToMany(Product::class, 'user_favorite_products')
            ->withTimestamps()
            ->orderBy('user_favorite_products.created_at', 'desc');
    }

    public function cartItems()
    {
        return $this->hasMany(CartItem::class);
    }

    public function findForPassport($identifier)
    {
        return UserAuth::orWhere('email', $identifier)->orWhere('username', $identifier)->first();
    }

    // 用户银行卡
    public function userBanks(){
        return $this->hasMany(UserBank::class, 'user_id');
    }

    // 收货地址
    public function userAddress(){
        return $this->hasMany(UserAddress::class, 'user_id');
    }

    // 默认地址排前面
    public function getUserAddress(){
        return $this->userAddress()->orderBy('is_default', 'desc')->orderBy('id', 'desc')->get();
    }

    // 用户账户信息
    public function balance(){
        return $this->hasOne(UserBalance::class, 'user_id');
    }


    // 流水记录
    public function balanceLogs(){
        return $this->hasMany(UserBalanceLog::class, 'user_id');
    }

    // 下级流水记录
    public function lowerBalanceLogs(){
        return $this->hasMany(UserBalanceLog::class, 'from_user_id');
    }

    // 提现记录
    public function withdraw(){
        return $this->hasMany(Withdraw::class, 'user_id');
    }

    // 申请代理记录
    public function applyAgents(){
        return $this->hasMany(UserApplyAgent::class, 'user_id');
    }

    // 用户上级，即推荐人
    public function userParent(){
        return $this->belongsTo(UserRelation::class, 'id', 'to_user_id');
    }

    public function agent(){
        return $this->belongsTo(Agent::class, 'agent_id');
    }

    // 下级
    public function lower(){
        return $this->hasMany(UserRelation::class, 'from_user_id');
    }

    public function getAvatarAttribute($value){
        if (empty($value) || Str::startsWith($value, ['data:image'])) {
            return $value;
        }
        if (Str::startsWith($value, ['http://', 'https://'])) {
            return $this->attributes['avatar'];
        }
        return Storage::disk('public')->url($value);
    }

    public function getQrcodeAttribute($value){
        if (empty($value) || Str::startsWith($value, ['http://', 'https://'])) {
            return $value;
        }
        return Storage::disk('public')->url($value);
    }

    public function getTypeShowAttribute(){
        return self::userTypes($this->type);
    }

    public function getAgentTimeAttribute($value){
        return $value ? date('Y-m-d', strtotime($value)) : '';
    }

    public function store(){
        return $this->hasOne(Store::class, 'user_id');
    }

    public function carte(){
        return $this->hasOne(Carte::class, 'uid');
    }

    public static function userTypes($type = '') {
        $data = [
            self::USER_TYPE_ONE => '普通用户',
            self::USER_TYPE_TWO => '企业会员',
        ];
        if($type === 'all'){
            return $data;
        }
        return $data[$type] ?? '';
    }

    // 判断支付密码是否为空
    public function getSetCashAttribute () {
        return $this->cash_password ? true: false;
    }

    // 企业名片
    public function companyCard(){
        return $this->hasOne(CompanyCard::class, 'uid')->where('status', CompanyCard::TYPE_NORMAL);
    }

    // 判断用户是否合法的企业用户
    public function isCompanyUser(){
        if(intval($this->type) === self::USER_TYPE_TWO && $this->enterprise_at->gt(Carbon::now())){
            return true;
        }
        return false;
    }

    // 名片的标签
    public function tags(){
        return $this->hasMany(Tag::class, 'uid');
    }

    public function getTagsNames(){
        $userTags = $this->tags()->where('status', Tag::TYPE_OWN)->pluck('title', 'id')->toArray();
        return $userTags;
    }

    // 收到的名片
    public function receiveCartes(){
        return $this->hasMany(ReceiveCarte::class, 'user_id');
    }

    //  检查企业状态
    public function getCompanyCardStatusAttribute(){
        // 修改企业名片状态
        $companyCard = $this->companyCard;
        if(intval($this->attributes['type']) === self::USER_TYPE_TWO && $this->enterprise_at->gt(Carbon::now())){
            if(!$companyCard){
                $companyCard = CompanyCard::addDefaultCompanyCard($this->id, '', $this->avatar);
            }
            if($companyCard && $companyCard->status !== CompanyCard::TYPE_DELETE && $companyCard->status === CompanyCard::TYPE_EXPIRE){
                $companyCard->status = CompanyCard::TYPE_NORMAL; // 正常
                $companyCard->save();
            }
            return true;
        }

        if($companyCard && $companyCard->status !== CompanyCard::TYPE_DELETE && $companyCard->status === CompanyCard::TYPE_NORMAL){
            $companyCard->status = CompanyCard::TYPE_EXPIRE; // 过期
            $companyCard->save();
        }
        return false;
    }


    // 开通企业会员记录
    public function companyCardLog(){
        return $this->hasMany(CompanyCardLog::class, 'user_id');
    }

    // 名片完善情况
    public function getPerfectAttribute(){
        $carte = $this->carte;
        if(!$carte){
//            return self::INCOMPLETE; // 信息不全
            return self::TO_BE_IMPROVED; // 待完善
        }
        // 信息不全验证字段
//        $incomplete = ['name', 'company_name', 'phone', 'position', 'industry_id'];
//        foreach ($incomplete as $field){
//            if(empty($carte->{$field})){
//                return self::INCOMPLETE; // 信息不全
//            }
//        }
        // 待完善验证字段
//        $toBeImproved = ['avatar', 'wechat', 'email', 'introduction', 'address_title'];
        // 姓名， 公司， 手机号 即为完善
        $toBeImproved = ['name', 'company_name', 'phone'];
        foreach($toBeImproved as $field){
            if(empty($carte->{$field})){
                return self::TO_BE_IMPROVED; // 待完善
            }
        }
        return self::COMPLETE_PERFECTION;
    }
}
