<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/22
 * Time: 15:30
 */

namespace App\Models\Traits;

use App\Models\Area;

trait AreaTrait
{
    static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::saving(function ($area){
            // 编辑详细信息
            $areaInfo = Area::query()->whereIn('code', [
                $area->province, $area->city, $area->district
            ])->pluck('name')->toArray();
            $areaInfo[] = $area->address;
            $area->full_address = implode('-', $areaInfo);
        });
    }

    // 省
    public function areaProvince(){
        return $this->belongsTo(Area::class, 'province', 'code');
    }

    // 市
    public function areaCity(){
        return $this->belongsTo(Area::class, 'city', 'code');
    }

    // 地区
    public function areaDistrict(){
        return $this->belongsTo(Area::class, 'district', 'code');
    }
}